name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip git

      - name: Install buildozer
        run: |
          pip install buildozer
          pip install cython

      - name: Initialize buildozer
        run: |
          buildozer init || true

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
